# Site settings
title: Dwinnn Speaks
subtitle: by Dan Nguyen
email: dwinnnspeaks@gmail.com
description: "test"
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl:
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: San Jose
state: CA
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/dnguyen800/home-assistant-configuration-example
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: https://www.linkedin.com/in/dwinnn
pinterest_url:
slack_url:
twitter_url: 
email_url: mailto:dwinnnspeaks@gmail.com
youtube_url: https://www.youtube.com/channel/UC1O-WwXbjHTKVT_j--r7MRQ

# Build settings
markdown: kramdown

# Dan's changes
# To build css customizations from _sass directory
sass:
    sass_dir: _sass

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"